version: "3"
services:

  keepair_master:
    container_name: keepair_master
    build:
      dockerfile: dev.Dockerfile
      context: docker/primary
    tty: true
    environment:
      - PORT=9000
    ports:
      - "9000:9000"
    volumes:
      - .:/root
    mem_limit: 1024m
    networks:
      - keepair_network

  keepair_worker_1:
    container_name: keepair_worker_1
    build:
      dockerfile: dev.Dockerfile
      context: ./docker/worker
    tty: true
    environment:
      - PORT=9001
      - MASTER_NODE_URL=http://keepair_master:9000
    ports:
      - "9001:9001"
    volumes:
      - .:/root
    mem_limit: 1024m
    networks:
      - keepair_network

  keepair_worker_2:
    container_name: keepair_worker_2
    build:
      dockerfile: dev.Dockerfile
      context: ./docker/worker
    tty: true
    environment:
      - PORT=9002
      - MASTER_NODE_URL=http://keepair_master:9000
    ports:
      - "9002:9002"
    volumes:
      - .:/root
    mem_limit: 1024m
    networks:
      - keepair_network

networks:
  keepair_network:
    name: keepair_network
